trigger:
  batch: true
  branches:
    include:
    - main

resources:
- repo: self

pool: containerBuilder

variables:
  RegistryName: saks01weuacrpgpgo5qvmwo
  RepositoryName: aapp/images
  ImageName: amsterdam-app-backend

steps:
- task: PowerShell@2
  displayName: Get version
  inputs:
    targetType: 'inline'
    script: |
      $version = Get-Content -Path $(Build.SourcesDirectory)\.version
      Write-Host "##vso[task.setvariable variable=version]$version"      

- task: Bash@3
  displayName: Build and push an image to container registry
  inputs:
      targetType: 'inline'
      script: |
            az login --identity
            az acr login --name $(RegistryName)
            docker build -t $(RegistryName).azurecr.io/$(RepositoryName)/$(ImageName):$(GitVersion.FullSemVer) .
            docker push $(RegistryName).azurecr.io/$(RepositoryName)/$(ImageName):$(GitVersion.FullSemVer)
            az acr repository show-tags --name $(RegistryName) --repository $(RepositoryName)/$(ImageName)     