trigger:
  batch: true
  branches:
    include:
    - main

resources:
- repo: self

pool: containerBuilder

variables:
  RegistryName: saks01weuacrpgpgo5qvmwo
  RepositoryName: aapp/images
  ImageName: amsterdam-app-backend

steps:
- task: Bash@3
  displayName: Build and push an image to container registry
  inputs:
      targetType: 'inline'
      script: |
            az login --identity
            az acr login --name $(RegistryName)
            docker build -t $(RegistryName).azurecr.io/$(RepositoryName)/$(ImageName):$(build.BuildNumber) .
            docker push $(RegistryName).azurecr.io/$(RepositoryName)/$(ImageName):$(build.BuildNumber)
            az acr repository show-tags --name $(RegistryName) --repository $(RepositoryName)/$(ImageName)     