trigger:
  batch: true
  branches:
    include:
      - main

jobs:
  - job: "Publish"

    resources:
      - repo: self

    pool: containerBuilder

    variables:
      RegistryName: saks01weuacrpgpgo5qvmwo
      RepositoryName: aapp/images
      ImageName: amsterdam-app-backend
      ImageVersion: 0.0.1

    steps:
      - task: Bash@3
        displayName: Get version
        inputs:
          targetType: "inline"
          script: |
            echo "##vso[task.setvariable variable=ImageVersion]$(cat $(Build.Repository.LocalPath)/.version)"

      - task: Bash@3
        displayName: Build and push an image to container registry
        inputs:
          targetType: "inline"
          script: |
            az login --identity
            az acr login --name $(RegistryName)
            docker build -t $(RegistryName).azurecr.io/$(RepositoryName)/$(ImageName):$(ImageVersion) .
            docker push $(RegistryName).azurecr.io/$(RepositoryName)/$(ImageName):$(ImageVersion)
            az acr repository show-tags --name $(RegistryName) --repository $(RepositoryName)/$(ImageName)
  - job: "Push_to_Github"
    timeoutInMinutes: 30
    pool:
      vmImage: macOS-12
    variables:
      - group: github-authorization
    steps:
      - template: ./pipelines/templates/push-repo-to-github.yml
        parameters:
          repository: "amsterdam-app-backend"
          sshKeySecureFile: "Construction-Work-github-ssh"
          sshPublicKey: $(sshPublicKeyConstructionWork)
