version: '3.7'

services:
  # POSTGRES DATABASE SERVER
  db:
    image: postgres:13
    volumes:
      - ${POSTGRES_VOLUME}/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRESS_PORT:-5432}:5432" 
    restart: always

  # BACKEND_API (api/web)
  api-server:
    image: ${TAG}
    command: bash /code/init.sh
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=db
      - WEB_USERNAME=${WEB_USERNAME}
      - WEB_PASSWORD=${WEB_PASSWORD}
      - APP_TOKEN=${APP_TOKEN}
      - AES_SECRET=${AES_SECRET}
      - API_PORT=${API_PORT}
      - UNITTEST=true
    volumes:
      - ${fcm_credential_path}:/code/fcm_credentials.json
      - ${env_path}:/code/env
    ports:
      - "${API_PORT:-8000}:${API_PORT:-8000}"
    depends_on:
      - db
    restart: always
