# Generated by Django 4.2.4 on 2023-10-11 16:46

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import construction_work.models.project_manager


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "identifier",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("url", models.CharField(default="", max_length=1000, unique=True)),
                (
                    "mime_type",
                    models.CharField(default="application/pdf", max_length=100),
                ),
                ("data", models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.BinaryField()),
                (
                    "description",
                    models.CharField(
                        blank=True, default=None, max_length=1000, null=True
                    ),
                ),
                ("width", models.IntegerField()),
                ("height", models.IntegerField()),
                ("aspect_ratio", models.FloatField()),
                ("coordinates", models.JSONField(blank=True, default=None, null=True)),
                ("mime_type", models.CharField(default="image/jpg", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_id", models.BigIntegerField(unique=True)),
                ("active", models.BooleanField(blank=True, default=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, db_index=True, max_length=1000, null=True
                    ),
                ),
                ("sections", models.JSONField(blank=True, default=dict, null=True)),
                ("contacts", models.JSONField(blank=True, default=list, null=True)),
                ("timeline", models.JSONField(blank=True, default=dict, null=True)),
                ("image", models.JSONField(blank=True, default=dict, null=True)),
                ("images", models.JSONField(blank=True, default=list, null=True)),
                ("url", models.URLField(blank=True, max_length=2048, null=True)),
                (
                    "creation_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "modification_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("publication_date", models.DateTimeField(default=None, null=True)),
                ("expiration_date", models.DateTimeField(default=None, null=True)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="ProjectManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "manager_key",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        validators=[
                            construction_work.models.project_manager.AmsterdamEmailValidator()
                        ],
                    ),
                ),
                (
                    "projects",
                    models.ManyToManyField(blank=True, to="construction_work.project"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WarningMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=1000)),
                ("body", models.TextField()),
                ("publication_date", models.DateTimeField(auto_now_add=True)),
                ("modification_date", models.DateTimeField(auto_now=True)),
                (
                    "author_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="construction_work.project",
                    ),
                ),
                (
                    "project_manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="construction_work.projectmanager",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WarningImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_main", models.BooleanField(default=False)),
                ("images", models.ManyToManyField(to="construction_work.image")),
                (
                    "warning",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="construction_work.warningmessage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1000)),
                ("body", models.TextField(blank=True, null=True)),
                ("publication_date", models.DateTimeField(auto_now_add=True)),
                (
                    "warning",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="construction_work.warningmessage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=200, unique=True)),
                (
                    "firebase_token",
                    models.CharField(max_length=1000, null=True, unique=True),
                ),
                ("os", models.CharField(blank=True, max_length=7, null=True)),
                ("last_access", models.DateTimeField(auto_now=True)),
                (
                    "followed_projects",
                    models.ManyToManyField(blank=True, to="construction_work.project"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("article_id", models.BigIntegerField(unique=True)),
                ("active", models.BooleanField(default=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=1000,
                        null=True,
                    ),
                ),
                ("intro", models.TextField(blank=True, default=None, null=True)),
                ("body", models.TextField(blank=True, default=None, null=True)),
                ("image", models.JSONField(blank=True, default=None, null=True)),
                (
                    "type",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                ("url", models.URLField(blank=True, max_length=2048, null=True)),
                (
                    "creation_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "modification_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("publication_date", models.DateTimeField(default=None, null=True)),
                ("expiration_date", models.DateTimeField(default=None, null=True)),
                ("projects", models.ManyToManyField(to="construction_work.project")),
            ],
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("firebase_token__isnull", True),
                    models.Q(("firebase_token", ""), _negated=True),
                    _connector="OR",
                ),
                name="firebase_token_unique_or_null",
            ),
        ),
    ]
