# Generated by Django 4.2.4 on 2023-09-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("construction_work", "0002_remove_project_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=200, unique=True)),
                (
                    "followed_projects",
                    models.ManyToManyField(to="construction_work.project"),
                ),
            ],
        ),
    ]
