# Generated by Django 4.2.4 on 2023-10-18 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("construction_work", "0002_project_coordinates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warningmessage",
            name="project_manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="construction_work.projectmanager",
            ),
        ),
    ]
