# Generated by Django 4.2.4 on 2023-09-21 16:04

from django.db import migrations


def translate_followed_projects_to_device_model(apps, _):
    FollowedProject = apps.get_model("construction_work", "followedproject")
    Device = apps.get_model("construction_work", "device")
    Project = apps.get_model("construction_work", "project")

    all_followed_projects = FollowedProject.objects.all()

    for fp in all_followed_projects:
        project = Project.objects.filter(project_id=fp.projectid).first()

        device = Device.objects.filter(device_id=fp.deviceid).first()
        if device is None:
            device = Device(device_id=fp.deviceid)
            device.save()
    
        device.followed_projects.add(project)

    

def reverse_device_model_to_followed_projects(apps, _):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("construction_work", "0003_device"),
    ]

    operations = [migrations.RunPython(translate_followed_projects_to_device_model, reverse_device_model_to_followed_projects)]
