# Generated by Django 4.2.4 on 2023-09-27 11:06

from django.db import migrations, models
import django.db.models.deletion


def move_device_ids(apps, _):
    FirebaseToken = apps.get_model("construction_work", "firebasetoken")
    Device = apps.get_model("construction_work", "device")
    tokens = FirebaseToken.objects.all()
    for t in tokens:
        device = Device.objects.filter(device_id=t.deviceid).first()
        t.device = device
        t.save()


class Migration(migrations.Migration):

    dependencies = [
        ("construction_work", "0004_followed_projects_to_device_model"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MobilePhoneAccessLog",
        ),
        migrations.RenameField(
            model_name="firebasetoken",
            old_name="firebasetoken",
            new_name="firebase_token",
        ),
        migrations.AddField(
            model_name="device",
            name="last_access",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="firebasetoken",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="construction_work.device",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(move_device_ids),
        migrations.RemoveField(
            model_name="firebasetoken",
            name="deviceid",
        ),
        migrations.AlterField(
            model_name="firebasetoken",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="construction_work.device",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="firebasetoken",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=None,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
    ]
