# Generated by Django 4.2.4 on 2023-10-18 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("construction_work", "0004_rename_article_id_article_foreign_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="project_id",
            new_name="foreign_id",
        ),
    ]
