# Generated by Django 4.2.4 on 2023-10-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("construction_work", "0005_rename_project_id_project_foreign_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="last_seen",
            field=models.DateTimeField(blank=True),
        ),
    ]
