# Generated by Django 4.2.4 on 2023-09-28 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("construction_work", "0005_alter_device_followed_projects"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MobilePhoneAccessLog",
        ),
        migrations.RenameField(
            model_name="firebasetoken",
            old_name="firebasetoken",
            new_name="firebase_token",
        ),
        migrations.RemoveField(
            model_name="firebasetoken",
            name="deviceid",
        ),
        migrations.AddField(
            model_name="device",
            name="firebase_token",
            field=models.CharField(max_length=1000, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="device",
            name="last_access",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="device",
            name="os",
            field=models.CharField(blank=True, null=True, max_length=7),
        ),
        migrations.AddField(
            model_name="firebasetoken",
            name="device",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="construction_work.device",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="firebasetoken",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=None,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("firebase_token__isnull", True),
                    models.Q(("firebase_token", ""), _negated=True),
                    _connector="OR",
                ),
                name="firebase_token_unique_or_null",
            ),
        ),
    ]
