# Generated by Django 4.2.4 on 2023-11-22 14:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("construction_work", "0006_alter_project_last_seen"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Asset",
        ),
    ]
