# Generated by Django 4.2.4 on 2023-09-28 12:20

from django.db import migrations


def transfer_firebase_tokens(apps, _):
    """Transfer firebase tokens to device table"""
    FirebaseToken = apps.get_model("construction_work", "firebasetoken")
    tokens = FirebaseToken.objects.all()
    for t in tokens:
        t.device.firebase_token = t.firebase_token
        t.device.os = t.os
        t.device.save()

def do_nothing(apps, _):
    """After model is removed data is removed, so no turning back"""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("construction_work", "0006_delete_mobilephoneaccesslog_and_more"),
    ]

    operations = [
        migrations.RunPython(transfer_firebase_tokens, do_nothing),
        migrations.DeleteModel(
            name="FirebaseToken",
        ),
    ]
