# Generated by Django 4.2.4 on 2023-09-27 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("construction_work", "0006_alter_device_followed_projects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="firebasetoken",
            name="device",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="construction_work.device",
            ),
        ),
    ]
