# Generated by Django 4.2.4 on 2023-10-04 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "construction_work",
            "0009_remove_image_url_remove_warningmessage_identifier_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="identifier",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="news_identifier",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="project_identifier",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="warning_identifier",
        ),
        migrations.AddField(
            model_name="notification",
            name="article",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="construction_work.article",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=None,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="notification",
            name="project",
            field=models.ForeignKey(
                blank=True,
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="construction_work.project",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="notification",
            name="warning",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="construction_work.warningmessage",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="body",
            field=models.TextField(),
        ),
    ]
