# Generated by Django 4.2.4 on 2023-10-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "construction_work",
            "0011_remove_image_identifier_remove_image_size_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="filename",
        ),
        migrations.RemoveField(
            model_name="warningmessage",
            name="images",
        ),
        migrations.AlterField(
            model_name="image",
            name="coordinates",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="description",
            field=models.CharField(
                blank=True, default=None, max_length=1000, null=True
            ),
        ),
    ]
