# Generated by Django 4.2.4 on 2023-10-10 15:05

from datetime import datetime

import django.utils.timezone
from django.db import migrations, models


def set_datetime(apps, _):
    """Transfer firebase tokens to device table"""
    project = apps.get_model("construction_work", "project")
    projects = project.objects.all()
    for p in projects:
        p.creation_date = datetime.now()
        p.modification_date = datetime.now()
        p.save()


def do_nothing(apps, _):
    """After model is removed data is removed, so no turning back"""
    pass


class Migration(migrations.Migration):
    dependencies = [
        (
            "construction_work",
            "0012_remove_image_filename_remove_warningmessage_images_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="body",
            new_name="sections",
        ),
        migrations.AlterField(
            model_name="project",
            name="sections",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.RemoveField(
            model_name="project",
            name="content_html",
        ),
        migrations.RemoveField(
            model_name="project",
            name="coordinates",
        ),
        migrations.RemoveField(
            model_name="project",
            name="district_id",
        ),
        migrations.RemoveField(
            model_name="project",
            name="news",
        ),
        migrations.AddField(
            model_name="project",
            name="image",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="timeline",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="url",
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="active",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="contacts",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="images",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.RunPython(set_datetime, do_nothing),
        migrations.AlterField(
            model_name="project",
            name="modification_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="project",
            name="creation_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="project",
            name="expiration_date",
            field=models.DateField(default=None, null=True),
        ),
        migrations.RemoveField(
            model_name="project",
            name="project_id",
        ),
        migrations.AddField(
            model_name="project",
            name="project_id",
            field=models.IntegerField(blank=False, unique=True, null=False),
        ),
        migrations.AlterField(
            model_name="project",
            name="subtitle",
            field=models.CharField(blank=True, db_index=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(blank=True, db_index=True, default="", max_length=1000, null=True),
        ),
    ]
