# Generated by Django 4.2.4 on 2023-10-10 17:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        (
            "construction_work",
            "0013_remove_project_body_remove_project_content_html_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="creation_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="article",
            name="expiration_date",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="modification_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="article",
            name="publication_date",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=1000, null=True
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="url",
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="last_seen",
            field=models.DateTimeField(
                auto_now=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
