# Generated by Django 4.2.4 on 2023-10-11 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("construction_work", "0015_remove_projectmanager_identifier_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="article",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="project",
        ),
        migrations.AlterField(
            model_name="notification",
            name="body",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="warning",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="construction_work.warningmessage",
            ),
            preserve_default=False,
        ),
    ]
