# Generated by Django 4.2.4 on 2023-09-14 11:25

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("identifier", models.CharField(max_length=100)),
                ("project_type", models.CharField(default="", max_length=100)),
                ("url", models.CharField(blank=True, default="", max_length=1000)),
                (
                    "title",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=1000
                    ),
                ),
                (
                    "publication_date",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("body", models.JSONField(default=dict, null=True)),
                ("images", models.JSONField(default=list, null=True)),
                ("assets", models.JSONField(default=list, null=True)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("active", models.BooleanField(blank=True, default=True)),
                ("type", models.CharField(default="news", max_length=30)),
            ],
            options={
                "ordering": ["publication_date"],
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "identifier",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("url", models.CharField(default="", max_length=1000, unique=True)),
                (
                    "mime_type",
                    models.CharField(default="application/pdf", max_length=100),
                ),
                ("data", models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name="FirebaseToken",
            fields=[
                (
                    "deviceid",
                    models.CharField(
                        max_length=200, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("firebasetoken", models.CharField(max_length=1000, unique=True)),
                ("os", models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name="FollowedProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deviceid", models.CharField(max_length=200)),
                ("projectid", models.CharField(default="", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "identifier",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("size", models.CharField(max_length=10)),
                ("url", models.CharField(max_length=1000, unique=True)),
                ("filename", models.CharField(max_length=1000)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=1000),
                ),
                ("mime_type", models.CharField(default="image/jpg", max_length=100)),
                ("data", models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name="MobilePhoneAccessLog",
            fields=[
                (
                    "deviceid",
                    models.CharField(
                        max_length=200, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("last_access", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "project_id",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "active",
                    models.BooleanField(blank=True, db_index=True, default=True),
                ),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("publication_date", models.DateField(default=None)),
                ("modification_date", models.DateField(default=None)),
                ("url", models.CharField(blank=True, default="", max_length=1000)),
                (
                    "title",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=1000
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(db_index=True, max_length=1000, null=True),
                ),
                ("body", models.JSONField(default=list, null=True)),
                ("content_html", models.TextField()),
                ("district_id", models.IntegerField(default=None)),
                ("coordinates", models.JSONField(default=dict, null=True)),
                ("images", models.JSONField(default=list, null=True)),
                ("contacts", models.JSONField(default=list, null=True)),
                ("news", models.JSONField(default=list, null=True)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="ProjectManager",
            fields=[
                (
                    "identifier",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=60, unique=True)),
                (
                    "projects",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=40), size=None
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WarningMessage",
            fields=[
                (
                    "identifier",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=1000)),
                ("body", models.CharField(max_length=1000)),
                ("project_manager_id", models.CharField(max_length=100)),
                (
                    "images",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.JSONField(default=dict, null=True), size=None
                    ),
                ),
                ("publication_date", models.DateTimeField(auto_now_add=True)),
                ("modification_date", models.DateTimeField(auto_now_add=True)),
                (
                    "author_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "project_identifier",
                    models.OneToOneField(
                        db_column="project_identifier",
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="construction_work.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "identifier",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=1000)),
                ("body", models.CharField(max_length=1000)),
                ("news_identifier", models.CharField(max_length=100, null=True)),
                ("warning_identifier", models.UUIDField(null=True)),
                ("publication_date", models.DateTimeField(auto_now_add=True)),
                (
                    "project_identifier",
                    models.ForeignKey(
                        db_column="project_identifier",
                        db_index=False,
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="construction_work.project",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="followedproject",
            constraint=models.UniqueConstraint(
                fields=("deviceid", "projectid"), name="deviceid_and_projectid"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="project_identifier",
            field=models.ForeignKey(
                db_column="project_identifier",
                on_delete=django.db.models.deletion.CASCADE,
                to="construction_work.project",
            ),
        ),
        migrations.AddConstraint(
            model_name="article",
            constraint=models.UniqueConstraint(
                fields=("identifier", "project_identifier"),
                name="identifier_and_project_identifier",
            ),
        ),
    ]
