# Generated by Django 4.2.4 on 2023-09-14 14:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("construction_work", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="url",
        ),
    ]
