# Generated by Django 4.2.4 on 2023-09-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("construction_work", "0004_followed_projects_to_device_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="followed_projects",
            field=models.ManyToManyField(blank=True, to="construction_work.project"),
        ),
    ]
