# Generated by Django 4.2.4 on 2023-09-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("construction_work", "0007_transfer_firebase_tokens"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={},
        ),
        migrations.RemoveConstraint(
            model_name="article",
            name="identifier_and_project_identifier",
        ),
        migrations.RemoveField(
            model_name="article",
            name="assets",
        ),
        migrations.RenameField(
            model_name="article",
            old_name="identifier",
            new_name="article_id",
        ),
        migrations.RemoveField(
            model_name="article",
            name="images",
        ),
        migrations.RemoveField(
            model_name="article",
            name="project_identifier",
        ),
        migrations.RemoveField(
            model_name="article",
            name="project_type",
        ),
        migrations.AlterField(
            model_name="article",
            name="article_id",
            field=models.BigIntegerField(default=None, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="article",
            name="creation_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="expiration_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="intro",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="modification_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="projects",
            field=models.ManyToManyField(to="construction_work.project"),
        ),
        migrations.AlterField(
            model_name="article",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="body",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="last_seen",
            field=models.DateTimeField(auto_now=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="article",
            name="publication_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="type",
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="url",
            field=models.CharField(
                blank=True, default=None, max_length=1000, null=True
            ),
        ),
    ]
