# Generated by Django 4.2.4 on 2023-10-02 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("construction_work", "0008_alter_article_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="url",
        ),
        migrations.RemoveField(
            model_name="warningmessage",
            name="identifier",
        ),
        migrations.RemoveField(
            model_name="warningmessage",
            name="project_identifier",
        ),
        migrations.RemoveField(
            model_name="warningmessage",
            name="project_manager_id",
        ),
        migrations.AddField(
            model_name="warningmessage",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=None,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="warningmessage",
            name="project",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="construction_work.project",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="warningmessage",
            name="project_manager",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="construction_work.projectmanager",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="warningmessage",
            name="body",
            field=models.TextField(),
        ),
        migrations.RemoveField(
            model_name="warningmessage",
            name="images",
        ),
        migrations.AlterField(
            model_name="warningmessage",
            name="modification_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="warningmessage",
            name="images",
            field=models.ManyToManyField(blank=True, to="construction_work.image"),
        ),
    ]
