# Generated by Django 4.2.4 on 2023-10-11 11:16

import uuid

import django.db.models.deletion
from django.db import migrations, models

import construction_work.models.project_manager


class Migration(migrations.Migration):
    dependencies = [
        ("construction_work", "0014_alter_article_creation_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="warningmessage",
            name="project_manager",
        ),
        migrations.RemoveField(
            model_name="projectmanager",
            name="identifier",
        ),
        migrations.AddField(
            model_name="projectmanager",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=None,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="warningmessage",
            name="project_manager",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="construction_work.projectmanager",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projectmanager",
            name="manager_key",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="projectmanager",
            name="email",
            field=models.EmailField(
                max_length=254,
                validators=[construction_work.models.project_manager.AmsterdamEmailValidator()],
            ),
        ),
        migrations.RemoveField(
            model_name="projectmanager",
            name="projects",
        ),
        migrations.AddField(
            model_name="projectmanager",
            name="projects",
            field=models.ManyToManyField(blank=True, to="construction_work.project"),
        ),
    ]
