# Generated by Django 4.2.4 on 2023-10-11 16:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("construction_work", "0016_remove_notification_article_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FollowedProject",
        ),
    ]
